---
- name: Clone source repository
  become: yes
  git:
    repo: "{{ repo_url }}"
    dest: "{{ source_path }}"
    version: "{{ git_branch }}"   # SHA-1 hash, the literal string HEAD, a branch name, or a tag name
    update: yes  # Does a git pull if the repo already exists
    force: yes

- name: Install virtualenv packages
  become: yes
  pip:
    requirements: "{{ source_path }}/html/requirements.txt"
    virtualenv: "{{ source_path }}/html/env"
    virtualenv_python: python3
