---
- name: Template systemd gunicorn config
  template:
    src: templates/gunicorn.service.j2
    dest: /etc/systemd/system/gunicorn.service
    force: yes

- name: Start systemd app service
  systemd:
    name: gunicorn.service
    state: restarted
    enabled: yes
    daemon_reload: yes

- name: Template nginx global config
  template:
    src: templates/nginx.conf.j2
    dest: /etc/nginx/nginx.conf
    force: yes

- name: Template nginx site config
  template:
    src: templates/{{ site_conf_template }}
    dest: /etc/nginx/conf.d/{{ app_name }}.conf
    force: yes

- name: Move static favicon assets
  command: cp -r "/home/{{ ansible_ssh_user }}/{{ app_name }}/assets/favicon/." "{{ nginx_build_path }}"

- name: Add robots.txt for SEO & Indexing
  become: true
  copy:
    src: files/robots.txt
    dest: "{{ nginx_build_path }}/robots.txt"
    force: yes

- name: Ensure build directory has appropriate permissions
  become: yes
  file:
    path: "{{ nginx_build_path }}"
    state: directory
    mode: 0755
    owner: root
    group: root

- name: Restart nginx
  systemd:
    name: nginx
    state: restarted
    enabled: yes
    daemon_reload: yes

- name: Open firewall
  ufw:
    rule: allow
    name: Nginx Full
