---
# prepare system and update packages
- name: Update apt & cache
  become: true
  apt:
    upgrade: 'yes'
    update_cache: 'yes'
    force_apt_get: true
    cache_valid_time: 36000

- name: Install system package dependencies
  become: true
  apt:
    name: "{{ packages }}"
    state: latest
    update_cache: yes
    force_apt_get: true
