---
- name: Update apt & cache
  become: true
  apt:
    upgrade: "yes"
    update_cache: "yes"
    force_apt_get: true
    cache_valid_time: 36000

- name: Enable universe repository
  apt_repository:
    repo: "{{ item }}"
  loop:
    - "deb http://archive.ubuntu.com/ubuntu/ bionic universe"
    - "deb http://archive.ubuntu.com/ubuntu/ bionic-updates universe"
    - "deb http://security.ubuntu.com/ubuntu/ bionic-security universe"

- name: Add Certbot repository
  apt_repository:
    repo: ppa:certbot/certbot

- name: Install system package dependencies
  become: true
  apt:
    name: "{{ packages }}"
    state: latest
    update_cache: yes
    force_apt_get: true

- name: Upgrade pip core packages
  pip:
    name: "{{ pip_core }}"
    state: latest

- name: Install Python core requirements
  pip:
    name: "{{ python_core }}"
    state: present
