---
# defaults file for deploy

# application source code
repo_url: https://github.com/{{ github_user }}/{{ app_name }}.git

# system packages
packages:
  - python3-dev
  - python3-pip
  - git
  - tree
  - nginx
  - vim

pip_core:
  - pip
  - setuptools
  - wheel

python_core:
  - virtualenv
  - requests

subdomains: {}
  # - key: code
  #   value: "https://google.com"
  # - key: venue
  #   value: "https://"

nginx_build_path: /var/www/html
wsgi_path: wsgi

# environment variables
os_environment:
  - key: LC_ALL
    value: "C.UTF-8"
